<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <Compile Remove="Documents\**" />
    <Compile Remove="Files\**" />
    <Content Remove="Configurations\**" />
    <Content Remove="Documents\**" />
    <Content Remove="Files\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <EmbeddedResource Remove="Documents\**" />
    <EmbeddedResource Remove="Files\**" />
    <None Remove="Configurations\**" />
    <None Remove="Documents\**" />
    <None Remove="Files\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>
</Project>
