namespace CommandLineArgumentDemo_54;

using System;
using System.IO;

class Program
{
    //Bring the Folder Path: ..\bin\Release\<target-framework>\
    //Run the Command:      dotnet build -c Release
    //Execute the App:      MyConsoleApp.exe "D:\Output" "Result.txt"
    static void Main(string[] args)
    {
        // Expected arguments:
        // args[0] = Folder Path
        // args[1] = File Name

        if (args.Length < 2)
        {
            Console.WriteLine("Usage:");
            Console.WriteLine("MyConsoleApp.exe <FolderPath> <FileName>");
            return;
        }

        string folderPath = args[0];
        string fileName = args[1];

        // Create folder if it does not exist
        Directory.CreateDirectory(folderPath);

        string filePath = Path.Combine(folderPath, fileName);

        // Hard-coded content
        string content =
            "This is a hard-coded text file." + Environment.NewLine +
            "Generated by C# Console Application." + Environment.NewLine +
            "Release Mode with Command Arguments.";

        // Generate text file
        File.WriteAllText(filePath, content);

        Console.WriteLine($"File generated successfully:");
        Console.WriteLine(filePath);
    }
}