<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_061_01_CustomerManagement.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Inayat.Rehman\Downloads\CustomerManagementDemo1\CustomerManagementDemo\CustomerManagement.Core\Customer.cs" Link="Customer.cs" />
    <Compile Include="..\..\..\Inayat.Rehman\Downloads\CustomerManagementDemo1\CustomerManagementDemo\CustomerManagement.Core\CustomerService.cs" Link="CustomerService.cs" />
  </ItemGroup>

</Project>
